apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: consumer-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      #      hostNetwork: true
      #      dnsPolicy: "None"
      #      dnsConfig:
      #        nameservers:
      #         - 8.8.8.8
      #         - 10.96.0.10
      #        searches:
      #          - backend-uat.svc.cluster.local
      #          - svc.cluster.local
      #          - cluster.local
      containers:
        - name: consumer
          image: 10.133.70.221:5000/consumerapi-consumer-production:18
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Africa/Cairo"
          #        volumeMounts:
          #        - mountPath: "/var/www/Logs/Consumer"
          #          name: backend-consumer
          ports:
            - containerPort: 8070
          resources:
              requests:
                memory: "270Mi"
                cpu: "25m"
              limits:
                memory: "300Mi"
                cpu: "100m"
      #      nodeName: consumer-test-backend1
      #      nodeName: consumer-test-backend2
      #      volumes:
      #       - name: backend-consumer
      #         persistentVolumeClaim:
      #          claimName: claim-backend
      imagePullSecrets:
        - name: myregistrykey
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#              - matchExpressions:
#                  - key: kubernetes.io/hostname
#                    operator: In
#                    values:
#                      - k8s-con-wrkr-01.momkndc.corp
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: consumer-production
spec:
  ports:
    - name: http-consumer-production
      targetPort: 8070
      port: 8070
      nodePort: 30225
  selector:
    app: consumer
  type: NodePort
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: consumer-service
#  namespace: consumer-production
#spec:
#  selector:
#    app: consumer
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8070
