apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-fluent-bit-sidecar
  annotations:
    policies.kyverno.io/title: Inject fluent-bit sidecar for logs to Elasticsearch
    policies.kyverno.io/category: Logging
    policies.kyverno.io/subject: Pod,Deployment
    policies.kyverno.io/description: |
      Injects a fluent-bit sidecar to pods whose Deployment pod template has label `logging: enabled`.
      The sidecar tails this pod's container logs from the node via hostPath mounts and forwards them to Elasticsearch.
spec:
  background: false
  rules:
    - name: add-fluent-bit-sidecar
      match:
        resources:
          kinds:
            - Deployment
      preconditions:
        all:
          - key: "{{ request.object.spec.template.metadata.labels.logging }}"
            operator: Equals
            value: "enabled"
      mutate:
        patchStrategicMerge:
          spec:
            template:
              spec:
                containers:
                  - name: fluent-bit
                    image: fluent/fluent-bit:2.2
                    imagePullPolicy: IfNotPresent
                    command:
                      - /bin/sh
                      - -lc
                      - >-
                        exec fluent-bit \
                        -i tail -p path=/var/log/containers/${POD_NAME}_${POD_NAMESPACE}_*.log -p parser=cri \
                        -m '*' \
                        -o es -p host=${ELASTICSEARCH_HOST} -p port=${ELASTICSEARCH_PORT} -p index=${ELASTICSEARCH_INDEX} -p logstash_format=On -p replace_dots=On -p tls=${ELASTICSEARCH_TLS} -p http_user=${ELASTICSEARCH_USERNAME} -p http_passwd=${ELASTICSEARCH_PASSWORD}
                    env:
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: ELASTICSEARCH_HOST
                        valueFrom:
                          configMapKeyRef:
                            name: elasticsearch-settings
                            key: host
                      - name: ELASTICSEARCH_PORT
                        valueFrom:
                          configMapKeyRef:
                            name: elasticsearch-settings
                            key: port
                      - name: ELASTICSEARCH_INDEX
                        valueFrom:
                          configMapKeyRef:
                            name: elasticsearch-settings
                            key: index
                      - name: ELASTICSEARCH_TLS
                        valueFrom:
                          configMapKeyRef:
                            name: elasticsearch-settings
                            key: tls
                      - name: ELASTICSEARCH_USERNAME
                        valueFrom:
                          secretKeyRef:
                            name: elasticsearch-credentials
                            key: username
                      - name: ELASTICSEARCH_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: elasticsearch-credentials
                            key: password
                    volumeMounts:
                      - name: varlogcontainers
                        mountPath: /var/log/containers
                        readOnly: true
                      - name: varlogpods
                        mountPath: /var/log/pods
                        readOnly: true
                      - name: varlibdockercontainers
                        mountPath: /var/lib/docker/containers
                        readOnly: true
                    resources:
                      requests:
                        cpu: 50m
                        memory: 64Mi
                      limits:
                        cpu: 200m
                        memory: 256Mi
                    securityContext:
                      readOnlyRootFilesystem: true
                volumes:
                  - name: varlogcontainers
                    hostPath:
                      path: /var/log/containers
                  - name: varlogpods
                    hostPath:
                      path: /var/log/pods
                  - name: varlibdockercontainers
                    hostPath:
                      path: /var/lib/docker/containers

